#server:
#   port: 8081
#
#person:
##   lastName: zhangsan
#   age: 25
#   birth: 1994/5/9
#   boolean: false
##   maps: {k1: v1, k2: v2}
#   maps:
#     k1: v1
#     k2: v2
##   lists: [zhangsi,zhangwu]
#   lists:
#     - zhangsi
#     - zhangwu
#   dog:
#     name: 小狗
#     age: 3
#   lastname: zhangyi
